name: Github Secrets

on:
    workflow_dispatch: 

jobs:
    deplyment:
        runs-on: ubuntu-latest
        steps:
        -   name: Print secret
            run: |
                echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}"
                echo "i_dont_exist: ${{ secrets.i_dont_exist }}"

        -   name: Print secret as an environment variable
            run: |
                echo "MY_TOP_SECRET: $MY_TOP_SECRET"
            env:
                AZURE_CREDENTIALS: ${{ secrets.MY_TOP_SECRET }}
